### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by sbaldwin24** [svengiebel/atom-compile-less#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-compile-less](https://github.com/freshl/atom-compile-less) package, v0.6.0
### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of undefined

```
At /Users/sbaldwin/.atom/packages/atom-compile-less/lib/atom-compile-less.coffee:51

TypeError: Cannot read property 'substr' of undefined
  at atomCompileLess (/Users/sbaldwin/.atom/packages/atom-compile-less/lib/atom-compile-less.coffee:51:23)
  at atom-workspace.<anonymous> (/Users/sbaldwin/.atom/packages/atom-compile-less/lib/atom-compile-less.coffee:77:48)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```
### Commands

```
  3x -0:28.9 core:backspace (input.hidden-input)
     -0:06.3 core:copy (input.hidden-input)
  2x -0:06.0 core:backspace (input.hidden-input)
     -0:01.6 application:new-file (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```
### Config

```
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v1.2.6
editor-stats, v0.16.0
file-icon-supplement, v0.7.2
file-icons, v1.4.3
linter-csslint, v0.0.11
linter-less, v0.3.1
seti-monokai, v0.3.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by dkomando** [comment]
Happening on Windows 8.1 as well.
